# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='status',
            field=models.CharField(default='unsold', max_length=100),
        ),
    ]
