# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_propertydetails_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='agents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
