# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_propertydetails_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='agents',
            field=models.IntegerField(default=0),
        ),
    ]
