# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequests',
            name='requestedProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.PropertyDetails'),
        ),
    ]
