# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20171214_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
